import { mkdir, writeFile } from 'fs/promises';
import path from 'path';

interface CreatePluginScaffoldOptions {
  pluginId: string;
  targetDir: string;
  withFrontend: boolean;
}

interface ParsedPluginId {
  pluginId: string;
  publisher: string;
  segments: string[];
  packageName: string;
  directorySlug: string;
  displayName: string;
  locationId: string;
  routeId: string;
  commandId: string;
}

function assertValidPluginId(pluginId: string): ParsedPluginId {
  const trimmed = pluginId.trim();
  if (!/^[a-z0-9-]+(?:\.[a-z0-9-]+)+$/.test(trimmed)) {
    throw new Error('Plugin id must be a lowercase namespaced id like acme.demo');
  }

  const segments = trimmed.split('.');
  const [publisher, ...rest] = segments;
  const featureSlug = rest.join('-');
  const words = featureSlug.split('-').filter(Boolean);
  const displayName = words.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');

  return {
    pluginId: trimmed,
    publisher,
    segments: rest,
    packageName: `@${publisher}/plugin-${featureSlug}`,
    directorySlug: segments.join('-'),
    displayName,
    locationId: `${featureSlug}-hub`,
    routeId: 'home',
    commandId: 'ping',
  };
}

function packageJsonTemplate(parsed: ParsedPluginId, withFrontend: boolean): string {
  const pkg: Record<string, unknown> = {
    name: parsed.packageName,
    private: true,
    version: '0.1.0',
    type: 'module',
    exports: {
      '.': './index.mjs',
    },
    urucPlugin: {
      pluginId: parsed.pluginId,
      apiVersion: 2,
      kind: 'backend',
      entry: './index.mjs',
      publisher: parsed.publisher,
      displayName: parsed.displayName,
      description: `${parsed.displayName} venue module generated by uruc plugin create.`,
      venue: {
        moduleId: parsed.pluginId,
        namespace: parsed.pluginId,
        displayName: parsed.displayName,
        description: `${parsed.displayName} venue module.`,
      },
      permissions: [],
      dependencies: [],
      activation: ['startup'],
    },
  };

  if (withFrontend) {
    pkg.urucFrontend = {
      apiVersion: 1,
      entry: './frontend/plugin.ts',
    };
  }

  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function backendTemplate(parsed: ParsedPluginId): string {
  return `import { defineBackendPlugin } from '@uruc/plugin-sdk/backend';

const PLUGIN_ID = '${parsed.pluginId}';
const LOCATION_ID = '${parsed.locationId}';

export default defineBackendPlugin({
  pluginId: PLUGIN_ID,
  async setup(ctx) {
    await ctx.locations.register({
      id: LOCATION_ID,
      name: '${parsed.displayName} Hub',
      description: 'A generated V2 plugin location.',
    });

    await ctx.commands.register({
      id: '${parsed.commandId}',
      description: 'Return a minimal generated status payload.',
      inputSchema: {},
      controlPolicy: {
        controllerRequired: false,
      },
      locationPolicy: {
        scope: 'any',
      },
      handler: async (_input, runtimeCtx) => ({
        ok: true,
        pluginId: PLUGIN_ID,
        locationId: runtimeCtx.currentLocation ?? null,
        message: '${parsed.displayName} is online.',
      }),
    });
  },
});
`;
}

function frontendPluginTemplate(parsed: ParsedPluginId): string {
  return `import {
  INTRO_CARD_TARGET,
  LOCATION_PAGE_TARGET,
  PAGE_ROUTE_TARGET,
  defineFrontendPlugin,
} from '@uruc/plugin-sdk/frontend';

export default defineFrontendPlugin({
  pluginId: '${parsed.pluginId}',
  version: '0.1.0',
  contributes: [
    {
      target: PAGE_ROUTE_TARGET,
      payload: {
        id: '${parsed.routeId}',
        pathSegment: '${parsed.routeId}',
        shell: 'app',
        guard: 'auth',
        venue: {
          titleKey: 'generated:venue.title',
          descriptionKey: 'generated:venue.description',
          icon: 'landmark',
          category: 'else',
        },
        load: async () => ({ default: (await import('./PluginPage')).PluginPage }),
      },
    },
    {
      target: LOCATION_PAGE_TARGET,
      payload: {
        locationId: '${parsed.pluginId}.${parsed.locationId}',
        routeId: '${parsed.routeId}',
        titleKey: 'generated:venue.title',
        shortLabelKey: 'generated:venue.shortLabel',
        descriptionKey: 'generated:venue.description',
        icon: 'landmark',
        accent: 'var(--city-node-future)',
        venueCategory: 'else',
      },
    },
    {
      target: INTRO_CARD_TARGET,
      payload: {
        id: 'intro',
        titleKey: 'generated:intro.title',
        bodyKey: 'generated:intro.body',
        icon: 'landmark',
      },
    },
  ],
  translations: {
    en: {
      generated: {
        venue: {
          title: '${parsed.displayName} Hub',
          shortLabel: '${parsed.displayName}',
          description: 'A generated frontend entry for ${parsed.pluginId}.',
        },
        intro: {
          title: 'Generated plugin UI',
          body: 'This page was created by uruc plugin create.',
        },
      },
    },
    'zh-CN': {
      generated: {
        venue: {
          title: '${parsed.displayName} 枢纽',
          shortLabel: '${parsed.displayName}',
          description: '${parsed.pluginId} 的前端入口由 uruc plugin create 生成。',
        },
        intro: {
          title: '已生成的插件界面',
          body: '这个页面由 uruc plugin create 自动创建。',
        },
      },
    },
  },
});
`;
}

function frontendPageTemplate(parsed: ParsedPluginId): string {
  return `import { useState } from 'react';
import { usePluginRuntime } from '@uruc/plugin-sdk/frontend-react';

export function PluginPage() {
  const runtime = usePluginRuntime();
  const [result, setResult] = useState('');
  const [error, setError] = useState('');

  const runPing = async () => {
    setError('');
    try {
      const payload = await runtime.sendCommand<{ message: string }>('${parsed.pluginId}.${parsed.commandId}@v1');
      setResult(payload.message);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Command failed.');
    }
  };

  return (
    <div className="page-wrap main-grid">
      <section className="card control-section">
        <h1 className="title-card">${parsed.displayName} Hub</h1>
        <p className="section-sub">A minimal generated plugin page for ${parsed.pluginId}.</p>
        <p className="muted">Current location: {runtime.currentLocation ?? 'outside city'}</p>
        <div className="row" style={{ gap: 12, marginTop: 16 }}>
          <button type="button" className="btn primary" onClick={() => { void runPing(); }}>
            Run ping
          </button>
        </div>
        {result ? <div className="notice success" style={{ marginTop: 16 }}>{result}</div> : null}
        {error ? <div className="notice error" style={{ marginTop: 16 }}>{error}</div> : null}
      </section>
    </div>
  );
}
`;
}

function readmeTemplate(parsed: ParsedPluginId, withFrontend: boolean): string {
  return `# ${parsed.displayName}

Generated by \`uruc plugin create\`.

## Package

- Plugin ID: \`${parsed.pluginId}\`
- Package name: \`${parsed.packageName}\`
- Frontend entry: ${withFrontend ? '`enabled`' : '`disabled`'}

## Install

\`\`\`bash
cd packages/server
../../scripts/uruc.mjs configure
../../scripts/uruc.mjs plugin link <path-to-this-plugin>
../../scripts/uruc.mjs start
\`\`\`

## SDK imports

- Backend: \`@uruc/plugin-sdk/backend\`
- Frontend protocol: \`@uruc/plugin-sdk/frontend\`
- Frontend React helpers: \`@uruc/plugin-sdk/frontend-react\`
- Frontend HTTP helper: \`@uruc/plugin-sdk/frontend-http\`
`;
}

export async function createPluginScaffold(options: CreatePluginScaffoldOptions): Promise<{
  pluginId: string;
  packageName: string;
  targetDir: string;
}> {
  const parsed = assertValidPluginId(options.pluginId);
  const targetDir = path.resolve(options.targetDir);

  await mkdir(path.dirname(targetDir), { recursive: true });
  await mkdir(targetDir, { recursive: false });
  await writeFile(path.join(targetDir, 'package.json'), packageJsonTemplate(parsed, options.withFrontend), 'utf8');
  await writeFile(path.join(targetDir, 'index.mjs'), backendTemplate(parsed), 'utf8');
  await writeFile(path.join(targetDir, 'README.md'), readmeTemplate(parsed, options.withFrontend), 'utf8');

  if (options.withFrontend) {
    const frontendDir = path.join(targetDir, 'frontend');
    await mkdir(frontendDir, { recursive: true });
    await writeFile(path.join(frontendDir, 'plugin.ts'), frontendPluginTemplate(parsed), 'utf8');
    await writeFile(path.join(frontendDir, 'PluginPage.tsx'), frontendPageTemplate(parsed), 'utf8');
  }

  return {
    pluginId: parsed.pluginId,
    packageName: parsed.packageName,
    targetDir,
  };
}

export function defaultPluginScaffoldDir(serverPackageRoot: string, pluginId: string): string {
  const parsed = assertValidPluginId(pluginId);
  return path.resolve(serverPackageRoot, '..', 'plugins', parsed.directorySlug);
}
