import { readCliMeta } from '../lib/state.js';
import { printBanner } from '../lib/ui.js';
import type { CommandContext, UiLanguage } from '../lib/types.js';

const helpText: Record<UiLanguage, string[]> = {
  'zh-CN': [
    '用法: uruc <命令> [选项]',
    '',
    '推荐主流程:',
    '  1. uruc configure        首次建城或后续重配',
    '  2. uruc start [-b]       启动前会自动准备城市配置与 lock',
    '',
    '核心命令:',
    '  configure           主城配置向导（QuickStart 线性流程；Advanced 菜单式 hub，可直接管理插件）',
    '  build               构建 server + web',
    '  start [-b]          启动 Uruc（默认前台，-b 后台；自动同步城市 lock）',
    '  stop                停止可识别的本地实例或 systemd 服务',
    '  restart             重启后台实例或 systemd 服务',
    '  status              查看当前运行状态、地址、配置来源',
    '  logs                查看日志（默认跟随）',
    '  dashboard           打开当前网站主页',
    '  doctor              检查配置、端口、构建、管理员、插件、健康状态',
    '',
    '高级命令:',
    '  city init           手动初始化空城市配置（一般不再需要）',
    '  admin create        新建管理员',
    '  admin list          列出现有管理员',
    '  admin promote       提升用户为管理员',
    '  admin reset-password 重置管理员密码',
    '  admin users         列出用户',
    '  admin ban/unban     封禁或解封用户',
    '  admin agents        列出 Agent',
    '  admin freeze/unfreeze 冻结或解冻 Agent',
    '  admin kick          踢掉在线 Agent',
    '',
    '插件命令:',
    '  Runtime Management: plugin list | install | link | remove | unlink | enable | disable | update | rollback | inspect | validate | doctor | gc',
    '  Discovery:          plugin scan | plugin source list | add | remove',
    '  Authoring:          plugin create | plugin pack',
    '',
    '通用选项:',
    '  --json              输出机器可读 JSON',
    '  --lang <lang>       指定 help/configure 语言：zh-CN | en | ko',
  ],
  en: [
    'Usage: uruc <command> [options]',
    '',
    'Recommended flow:',
    '  1. uruc configure        First-time setup or later reconfiguration',
    '  2. uruc start [-b]       Start Uruc; city config and lock are prepared automatically',
    '',
    'Core commands:',
    '  configure           Guided city configuration (QuickStart is linear; Advanced is a menu hub with plugin controls)',
    '  build               Build server + web',
    '  start [-b]          Start Uruc (foreground by default; -b uses the managed background path, or systemd when a service is installed)',
    '  stop                Stop a recognized local Uruc instance or systemd service',
    '  restart             Restart the managed background process or systemd service',
    '  status              Show runtime state, URLs, and active config source',
    '  logs                Show logs (follow by default)',
    '  dashboard           Open the current site home page',
    '  doctor              Diagnose config, ports, build freshness, admin, plugins, health',
    '',
    'Advanced commands:',
    '  city init           Manually create an empty city config (usually not needed)',
    '  admin create | list | promote | reset-password | users | ban | unban',
    '  admin agents | freeze | unfreeze | kick',
    '',
    'Plugin commands:',
    '  Runtime Management: plugin list | install | link | remove | unlink | enable | disable | update | rollback | inspect | validate | doctor | gc',
    '  Discovery:          plugin scan | plugin source list | add | remove',
    '  Authoring:          plugin create | plugin pack',
    '',
    'Global options:',
    '  --json              Output machine-readable JSON',
    '  --lang <lang>       Help/configure language: zh-CN | en | ko',
  ],
  ko: [
    '사용법: uruc <명령> [옵션]',
    '',
    '권장 흐름:',
    '  1. uruc configure        최초 설정 또는 이후 재구성',
    '  2. uruc start [-b]       시작 전에 도시 설정과 lock 을 자동 준비',
    '',
    '핵심 명령:',
    '  configure           도시 설정 마법사 (QuickStart 는 선형 흐름, Advanced 는 플러그인 관리가 포함된 메뉴 허브)',
    '  build               server + web 빌드',
    '  start [-b]          Uruc 실행 (기본 포그라운드, -b 백그라운드; 도시 lock 자동 동기화)',
    '  stop                인식 가능한 로컬 Uruc 인스턴스 또는 systemd 서비스 중지',
    '  restart             관리 중인 백그라운드 프로세스 또는 systemd 서비스 재시작',
    '  status              현재 실행 상태, 주소, 사용 중인 설정 파일 표시',
    '  logs                로그 보기 (기본 follow)',
    '  dashboard           현재 사이트 홈 페이지 열기',
    '  doctor              설정, 포트, 빌드, 관리자, 플러그인, 상태 점검',
    '',
    '고급 명령:',
    '  city init           빈 도시 설정 파일을 수동으로 생성 (보통 불필요)',
    '  admin create | list | promote | reset-password | users | ban | unban',
    '  admin agents | freeze | unfreeze | kick',
    '',
    '플러그인 명령:',
    '  Runtime Management: plugin list | install | link | remove | unlink | enable | disable | update | rollback | inspect | validate | doctor | gc',
    '  Discovery:          plugin scan | plugin source list | add | remove',
    '  Authoring:          plugin create | plugin pack',
    '',
    '공통 옵션:',
    '  --json              JSON 출력',
    '  --lang <lang>       help/configure 언어: zh-CN | en | ko',
  ],
};

export async function runHelpCommand(context: CommandContext): Promise<void> {
  const lang = context.lang ?? readCliMeta().language ?? 'zh-CN';
  printBanner(lang, 'CLI');
  console.log(helpText[lang].join('\n'));
}
