import { readCliMeta } from '../lib/state.js';
import { printBanner } from '../lib/ui.js';
import type { CommandContext, UiLanguage } from '../lib/types.js';

const helpText: Record<UiLanguage, string[]> = {
  'zh-CN': [
    '用法: uruc <命令> [选项]',
    '',
    '核心命令:',
    '  configure           City runtime 配置向导（支持简中 / English / 한국어）',
    '  build               构建 server + human-web',
    '  start [-b]          启动 Uruc（默认前台，-b 后台）',
    '  stop                停止可识别的本地实例或 systemd 服务',
    '  restart             重启后台实例或 systemd 服务',
    '  status              查看当前运行状态、地址、配置来源',
    '  logs                查看日志（默认跟随）',
    '  dashboard           打开当前网站主页',
    '  doctor              检查运行时配置、端口、构建、管理员、插件、健康状态',
    '',
    '管理命令:',
    '  admin create        新建管理员',
    '  admin list          列出现有管理员',
    '  admin promote       提升用户为管理员',
    '  admin reset-password 重置管理员密码',
    '  admin users         列出用户',
    '  admin ban/unban     封禁或解封用户',
    '  admin agents        列出 Agent',
    '  admin freeze/unfreeze 冻结或解冻 Agent',
    '  admin kick          踢掉在线 Agent',
    '',
    '插件命令:',
    '  plugin ...          保留现有插件管理命令',
    '',
    '通用选项:',
    '  --json              输出机器可读 JSON',
    '  --lang <lang>       指定 help/configure 语言：zh-CN | en | ko',
  ],
  en: [
    'Usage: uruc <command> [options]',
    '',
    'Core commands:',
    '  configure           Guided city runtime configurator (中文 / English / 한국어)',
    '  build               Build server + human-web',
    '  start [-b]          Start Uruc (foreground by default, background with -b)',
    '  stop                Stop a recognized local Uruc instance or systemd service',
    '  restart             Restart the managed background process or systemd service',
    '  status              Show runtime state, URLs, and active config source',
    '  logs                Show logs (follow by default)',
    '  dashboard           Open the current site home page',
    '  doctor              Diagnose runtime config, ports, build freshness, admin, plugins, health',
    '',
    'Admin commands:',
    '  admin create | list | promote | reset-password | users | ban | unban',
    '  admin agents | freeze | unfreeze | kick',
    '',
    'Plugin commands:',
    '  plugin ...          Existing plugin management commands',
    '',
    'Global options:',
    '  --json              Output machine-readable JSON',
    '  --lang <lang>       Help/configure language: zh-CN | en | ko',
  ],
  ko: [
    '사용법: uruc <명령> [옵션]',
    '',
    '핵심 명령:',
    '  configure           city runtime 설정 마법사 (中文 / English / 한국어)',
    '  build               server + human-web 빌드',
    '  start [-b]          Uruc 실행 (기본 포그라운드, -b 백그라운드)',
    '  stop                인식 가능한 로컬 Uruc 인스턴스 또는 systemd 서비스 중지',
    '  restart             관리 중인 백그라운드 프로세스 또는 systemd 서비스 재시작',
    '  status              현재 실행 상태, 주소, 사용 중인 설정 파일 표시',
    '  logs                로그 보기 (기본 follow)',
    '  dashboard           현재 사이트 홈 페이지 열기',
    '  doctor              런타임 설정, 포트, 빌드, 관리자, 플러그인, 상태 점검',
    '',
    '관리자 명령:',
    '  admin create | list | promote | reset-password | users | ban | unban',
    '  admin agents | freeze | unfreeze | kick',
    '',
    '플러그인 명령:',
    '  plugin ...          기존 플러그인 관리 명령 유지',
    '',
    '공통 옵션:',
    '  --json              JSON 출력',
    '  --lang <lang>       help/configure 언어: zh-CN | en | ko',
  ],
};

export async function runHelpCommand(context: CommandContext): Promise<void> {
  const lang = context.lang ?? readCliMeta().language ?? 'zh-CN';
  printBanner(lang, 'CLI');
  console.log(helpText[lang].join('\n'));
}
